title: 'Connect Print | Developer Hub'
description: >
  Welcome to the Connect Print Directory developer hub. You'll find
  comprehensive guides and documentation to help you start working with
  Connect Print Directory as quickly as possible, as well as support if
  you get stuck. Let's jump right in!
dest: 'dist'
themeConfig:
  nav:
    - text: Home
      link: '/'
    - text: Guides
      items:
        - text: Single Sign On & OAuth
          link: '/guide/oauth'
